# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 2048
CPU = 2

Vagrant.configure("2") do |config|
   
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20220924.0.0"
  config.vm.provision :shell, path: "bootstrap-ubuntu.sh"
  # configure virtualbox
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
 
 
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     
	 #echo UPDATE PACKAGE ------------------------------.
	 sudo apt-get update
	 
	 echo INSTALLING PACKAGE: TREE ------------------------------.
     apt-get install tree -y
     
     echo INSTALLING PACKAGE: SNAPD ------------------------------.
     apt install snapd -y

     # install docker
     sudo apt-get update
     echo INSTALLING PACKAGE: DOCKER ------------------------------
     sudo snap install docker
     
	 sudo apt-get update
	 # see the documentation: https://microk8s.io/docs/getting-started
	 echo INSTALLING PACKAGE: MICROK8S ------------------------------.
     sudo snap install microk8s --classic
	 
	 echo "This should be done after that the machine start" ------------------------------
	 # This should be done after that the machine start
	 echo ADD USER GROUP:  microk8s ------------------------------
	 sudo usermod -a -G microk8s $USER
	 sudo chown -f -R $USER ~/.kube
	 echo SU $USER ------------------------------ 
	 su - $USER
	 
	 
     # Check the status	 
	 echo CHECK THE STATUS MICROK8S ------------------------------
	 microk8s status --wait-ready



	 
  SHELL
  
	
end
